version: '3.3'

services:
  mongodb-router-1:
    image: mongo:4.1.9
    command: mongos --bind_ip_all --configdb cfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019
    deploy:
      placement:
        constraints:
          - node.labels.db7 == true
    ports:
      - "27026:27017"
    volumes:
      - mongodb-router-1_data:/data/db
    networks:
      mongodb:
  mongodb-router-2:
    image: mongo:4.1.9
    command: mongos --bind_ip_all --configdb cfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019
    deploy:
      placement:
        constraints:
          - node.labels.db8 == true
    ports:
      - "27027:27017"
    volumes:
      - mongodb-router-2_data:/data/db
    networks:
      mongodb:
  mongodb-router-3:
    image: mongo:4.1.9
    command: mongos --bind_ip_all --configdb cfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019
    deploy:
      placement:
        constraints:
          - node.labels.db9 == true
    ports:
      - "27028:27017"
    volumes:
      - mongodb-router-3_data:/data/db
    networks:
      mongodb:

volumes:
  mongodb-router-1_data:
  mongodb-router-2_data:
  mongodb-router-3_data:

networks:
  mongodb:
    driver: overlay
    attachable: true

