version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  coordinator:
    build:
      context: coordinator
    environment:
      MQTT_ADDRESS: mqtt://mqtt:1883
    volumes:
      - ./config:/usr/src/app/config
    depends_on:
      - mqtt
  worker:
    build:
      context: worker
    environment:
      MQTT_ADDRESS: mqtt://mqtt:1883
    depends_on:
      - mqtt