version: '3.3'

services:
  cassandra:
    image: cassandra
    deploy:
      placement:
        constraints:
          - node.labels.cassandra == true
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

secrets:
  coordinator_config.json:
    file: ./config/cassandra_machine_small.json
volumes:
  cassandra_data:
