version: '3.3'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  coordinator:
    image: localhost:5000/db-test_coordinator
    deploy:
      placement:
        constraints:
          - node.labels.coordinator == true
    environment:
      MQTT_ADDRESS: mqtt://mqtt:1883
    depends_on:
      - mqtt
    secrets:
      - coordinator_config.json
    volumes:
      - ./stats/:/var/log/db-test/
  worker:
    image: localhost:5000/db-test_worker
    deploy:
      replicas: 6
      placement:
        constraints:
          - node.labels.worker == true
    environment:
      MQTT_ADDRESS: mqtt://mqtt:1883
    depends_on:
      - mqtt
