version: '3.3'

services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

secrets:
  coordinator_config.json:
    file: ./config/cassandra_machine_big.json
volumes:
  cassandra_data: