version: '3'

services:
  mongodb:
    image: mongo
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  coordinator:
    environment:
      CONFIG: "mongodb_machine_small.json"

volumes:
  mongodb_data: