version: '3.3'

services:
  mongodb:
    image: mongo:4.1.9
    command: mongod --bind_ip_all --slowms 10000
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      
volumes:
  mongodb_data:
