version: '3.3'

services:
  cassandra-seed:
    container_name: cassandra-seed-node
    image: cassandra
    deploy:
      placement:
        constraints:
          - node.labels.cassandra == true
    ports:
      - "9042:9042"
    volumes:
      - cassandra_seed_data:/var/lib/cassandra
    networks: 
      - cassandra
    
volumes:
  cassandra_seed_data:

networks: 
  cassandra:
    driver: overlay
    attachable: true