version: '3.3'

services:
  cassandra-node3:
    image: cassandra
    deploy:
      placement:
        constraints:
          - node.labels.db4 == true
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-node3
      CASSANDRA_SEEDS: "tasks.cassandra-seed"
    volumes:
      - cassandra_node3_data:/var/lib/cassandra
    networks: 
      cassandra:
    
volumes:
  cassandra_node3_data:

networks: 
  cassandra:
    driver: overlay
    attachable: true
