version: '3.3'

services:
  couchbase1:
    image: couchbase:community
    deploy:
      placement:
        constraints:
          - node.labels.db1 == true
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - couchbase1_data:/opt/couchbase/var
    networks:
      couchbase:
  couchbase2:
    image: couchbase:community
    deploy:
      placement:
        constraints:
          - node.labels.db2 == true
    ports:
      - "9091-9094:8091-8094"
      - "12210:11210"
    volumes:
      - couchbase2_data:/opt/couchbase/var
    networks:
      couchbase:
  couchbase3:
    image: couchbase:community
    deploy:
      placement:
        constraints:
          - node.labels.db3 == true
    ports:
      - "10091-10094:8091-8094"
      - "13210:11210"
    volumes:
      - couchbase3_data:/opt/couchbase/var
    networks:
      couchbase:

volumes:
  couchbase1_data:
  couchbase2_data:
  couchbase3_data:

networks:
  couchbase:
    driver: overlay
    attachable: true

