version: '3.3'

services:
  couchbase:
    image: couchbase:community
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var

secrets:
  coordinator_config.json:
    file: ./config/couchbase_machine_small.json
volumes:
  couchbase_data:
