version: '3.3'

services:
  mongodb:
    image: mongo
    command: mongod --bind_ip_all --slowms 10000
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

secrets:
  coordinator_config.json:
    file: ./config/mongodb_machine_big.json
volumes:
  mongodb_data:
